# Generated by Django 4.2.4 on 2024-01-15 17:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_alter_stream_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="bio",
            field=models.TextField(
                blank=True,
                default="Всем привет! Я ученик компании WorkBench!",
                null=True,
            ),
        ),
    ]
