# Generated by Django 4.2.4 on 2024-01-15 17:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0007_user_bio"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="address",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="city",
            field=models.CharField(
                choices=[
                    ("tse", "Астана"),
                    ("ala", "Алматы"),
                    ("kiev", "Киев"),
                    ("bishkek", "Бишкек"),
                    ("tashkent", "Ташкент"),
                ],
                default="tse",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="country",
            field=models.CharField(
                choices=[
                    ("kz", "Казахстан"),
                    ("ru", "Россия"),
                    ("ukr", "Украина"),
                    ("kg", "Кыргызстан"),
                    ("uz", "Узбекистан"),
                ],
                default="kz",
                max_length=15,
            ),
        ),
    ]
