# Generated by Django 4.2.4 on 2024-01-17 00:42

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0011_alter_user_city"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentOrderHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cash_method",
                    models.CharField(
                        choices=[
                            ("nal", "Наличными"),
                            ("send", "Перевод на карту"),
                            ("payment", "Оплата по реквизитам"),
                        ],
                        default="payment",
                        max_length=30,
                        verbose_name="cash_method",
                    ),
                ),
                (
                    "cash_count",
                    models.PositiveBigIntegerField(
                        blank=True, null=True, verbose_name="cash_count"
                    ),
                ),
                (
                    "bank",
                    models.CharField(
                        choices=[
                            ("kaspi_bank", "Kaspi Банк"),
                            ("halyk_bank", "Halyk банк"),
                            ("forte_bank", "Forte Банк"),
                            ("freedom", "Freedom Finance"),
                            ("simply", "Simply"),
                            ("bereke_bank", "Береке Банк"),
                            ("jusan_bank", "Jusan Bank"),
                        ],
                        max_length=255,
                        verbose_name="bank",
                    ),
                ),
                (
                    "created_date",
                    models.DateField(
                        default=datetime.datetime.now, verbose_name="date"
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "История покупок студентов",
                "verbose_name_plural": "Истории покупок студентов",
            },
        ),
    ]
