# Generated by Django 4.2.4 on 2023-08-31 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=155)),
                ("email", models.EmailField(max_length=254)),
                ("phone_number", models.PositiveIntegerField(null=True)),
                ("message", models.TextField(blank=True, max_length=500, null=True)),
                ("read", models.BooleanField(default=False)),
                ("timestamp", models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                "verbose_name": "Новая заявка",
                "verbose_name_plural": "Новые заявки",
            },
        ),
    ]
