# Generated by Django 4.2.4 on 2024-01-18 13:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="author_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
