# Generated by Django 4.2.4 on 2024-01-18 13:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_post_author_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="video",
            field=models.URLField(blank=True, null=True),
        ),
    ]
