# Generated by Django 5.0.1 on 2024-01-28 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='hashtag',
            field=models.CharField(choices=[('startups', 'Стартапы'), ('programming', 'Программирование'), ('digital', 'Цифровизация'), ('strategy', 'IT стратегия'), ('physics', 'Физика'), ('math', 'Математика'), ('business', 'IT Бизнес'), ('technology', 'Технологии'), ('lifehacks', 'Лайфхаки')], default='programming', max_length=255),
        ),
    ]
