# Generated by Django 4.2.4 on 2023-11-22 15:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("courses", "0018_remove_lesson_course"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="students",
            field=models.ManyToManyField(
                blank=True, related_name="notifications", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
