# Generated by Django 4.2.4 on 2024-01-16 23:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0021_alter_course_start_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
