# Generated by Django 4.2.4 on 2024-01-16 23:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0022_lesson_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="order",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
