# Generated by Django 4.2.4 on 2024-03-23 00:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0023_lesson_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="is_completed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="lesson",
            name="is_watched",
            field=models.BooleanField(default=False),
        ),
    ]
