# Generated by Django 4.2.4 on 2024-03-23 01:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0024_lesson_is_completed_lesson_is_watched"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="video",
            field=models.URLField(blank=True, null=True),
        ),
    ]
