# Generated by Django 4.2.4 on 2024-03-23 02:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0025_alter_lesson_video"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="stream_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="video",
            field=models.FileField(upload_to="videos/"),
        ),
    ]
