# Generated by Django 4.2.4 on 2024-03-24 09:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0028_lesson_home_work"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="stream_url",
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="title",
            field=models.CharField(max_length=400),
        ),
    ]
